### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FusionIX** [NotEnoughCoins/NotEnoughCoins#45]
Hello my forge 1.8.9 seems to be crashing when i load the game this is my mod folder:
![Mods](https://user-images.githubusercontent.com/96489091/146962363-ecbde372-013a-4d90-a394-8069ca8db359.PNG)

**Comment by RobotHanzo** [comment]
Please include your crash logs

**Comment by Alrich1125** [comment]
Update Patcher and Scrollable Tooltips that could be the cause of crash
