### ISSUE TITLE
client crash due to wrong call

### ISSUE THREAD

**Issue by koolade44** [NotEnoughCoins/NotEnoughCoins#49]
Newest source code throws net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft; error

Due to this line 
(Authenticator:81) Session session = Minecraft.getMinecraft().getSession();
attempting to call getMinecraft from init phase

- [ ] 

[crash-2022-01-20_15.35.40-client.txt](https://github.com/NotEnoughCoins/NotEnoughCoins/files/7909004/crash-2022-01-20_15.35.40-client.txt)

**Comment by RobotHanzo** [comment]
Did you build the jar by yourself? I never encountered this before

**Comment by koolade44** [comment]
> Did you build the jar by yourself? I never encountered this before

Yes I did i cant seem to figure out what's causing this the jar loads fine and is recognized by forge but doesn't load it just causes a crash
