### ISSUE TITLE
Mc crashes and bitdefender said this about the file: Java.Trojan.GenericGBA.31482

### ISSUE THREAD

**Issue by Lordtomato13** [NotEnoughCoins/NotEnoughCoins#55]
I have been using nec for about a month and everything went well until yesterday. I couldn't open my mc anymore with nec in my mods folder. Bitdefender blocked it and said: Java.Trojan.GenericGBA.31482
Mc crash report: invalid javaruntimeconfiguration

**Comment by mindlesslydev** [comment]
Not an issue with the mod, your antivirus is just bad
