### ISSUE TITLE
Commands not working when trying to enable flipper

### ISSUE THREAD

**Issue by takktical** [NotEnoughCoins/NotEnoughCoins#64]
Whenever I try to use `/nec toggle` I get a message saying "An unknown error occurred while attempting to perform this command". Other commands like `/nec minprofit` and `/nec mindemand` work, but toggling doesn't.
![nectoggle](https://github.com/NotEnoughCoins/NotEnoughCoins/assets/107150495/5cd5ef89-769d-4526-ab1d-08bc21f19e48)

**Comment by DarkMercyy** [comment]
same issue

**Comment by SlayerSlayz** [comment]
same issue, but doesnt even show the command list
