### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Vanshkiller** [NotEnoughCoins/NotEnoughCoins#68]
When ever I download NEC my game crashed I have try to different launcher but that also don't work pls help me anyone.

**Comment by mindlesslydev** [comment]
I don't believe this is an issue specifically with the project, rather an issue either on your machine or with how you downloaded the mod. Please seek support on the [Discord](https://notenoughcoins.net/discord). Please check faqs before opening a ticket.
